### ISSUE TITLE
Demo click does not trigger on Android Tablet only on Ipad

### ISSUE THREAD

**Issue by lpnkng** [LeadDyno/intercooler-js#42] opened 2015-03-21 07:28 UTC
I tested on Android 4.4.2 samsung tablet and ipad. Ipad is ok but impossible to click on Android tablet

**Comment by carsongross** [comment] 2015-03-23 17:20
Are you able to debug?  Are there any javascript errors?

I will try to test later today.

**Comment by carsongross** [comment] 2015-04-16 17:43
Closing, unable to reproduce.  If you can reproduce and give me platform info I'm happy to look at it.

**Closed by carsongross** 2015-04-16 17:43 UTC
