### ISSUE TITLE
100% CPU on the infinite scroll example

### ISSUE THREAD

**Issue by mafrosis** [LeadDyno/intercooler-js#126] opened 2016-10-07 10:18 UTC
I love the design idea behind intercooler. However, in trying out the examples I found that Chrome Helper process on my macbook was 100% CPU - and the culprit was `http://intercoolerjs.org/examples/infinitescroll.html`

FWIW I had scrolled a couple of times and then switched to code view before going to get a coffee.

**Comment by OvermindDL1** [comment] 2016-10-07 15:40
Hmm, I just profiled using the chrome profiler and the javascript is barely even noticed even while scrolling down substantially.  Can you use Chrome's profile to figure out what is spinning and/or send a copy?

**Comment by mafrosis** [comment] 2016-10-08 08:41
The mockjax call is happening repeatedly when you're scrolled even part way down the docs on the example. Even if you scroll back to the top, the calls continue going out. 

I had a quick look, but I don't see any way to temporarily disable the `scrolled-into-view` event.

A similar but different bug/feature I noticed on `docs.html#polling` section - if I leave my browser window open (as people do!) I managed to get up to `This span has polled 7984 times...`.

**Comment by OvermindDL1** [comment] 2016-10-08 20:46
Yep the polling just always goes unless you turn it on or off (which you can).  :-)

So it is the testing framework causing it?  I'm not experiencing the repeated calling.  I could potentially see it happen if the tab was backgrounded for a while considering how it works, but not just be scrolling.  Interesting...

**Comment by mafrosis** [comment] 2016-10-09 07:33
Just to be sure we're talking about the same thing here.. This is a problem I noticed on your code examples in the docs :)

0. Open up chrome dev tools console
1. Go to http://intercoolerjs.org/examples/infinitescroll.html
2. Don't scroll
3. Click "Source Code"
4. Scroll down just a tiny amount (maybe 2 mouse wheels)
5. See `mockjax` calls in the console
6. Watch them fun forever!

So how do you go about disabling an `ic-` attrib? For instance switch an `ic-poll` attrib off and on again?

**Comment by OvermindDL1** [comment] 2016-10-09 20:41
It can be enabled/disabled via the `ic-pause-polling attribute, from the manual:

> The second is the `ic-pause-polling` attribute, can be set to true to tell an element not to poll.

:-)

**Comment by OvermindDL1** [comment] 2016-10-09 20:44
And I see what you mean now, it is not spamming mockjax, but rather running once a second at the polling rate.  I think that would be expected although you could easily have it add/remove the `ic-pause-polling` attribute when out of view with a little javascript too.  :-)

Might make for a good built in option though, PR?  :-)

**Comment by mafrosis** [comment] 2016-10-10 07:01
I'm not sure I follow what feature you're suggesting.

This report isn't so much a bug, but poor design in your infinite scroll example that made it appear as though intercooler was overloading my machine! 💥 💻  Which kind of put my off on my first look at the lib.

If I find some time, I'll fix your example for you, but I'll be busy adding intercooler to my site first ;)

Thanks for the great lib

**Comment by OvermindDL1** [comment] 2016-10-10 16:26
Not my lib or my example page, just a user of intercooler.  ^.^

**Comment by carsongross** [comment] 2016-10-10 17:27
I'm going to reopen this, because I should fix the example.  I've seen it happen before.  It's something funky when you have infinite scroll going and you switch to where the element is hidden.  That's a valid (if rare) bug, IMO.

**Comment by RazvanB** [comment] 2016-12-05 22:45
![infinitescrolling_ex](https://cloud.githubusercontent.com/assets/1068284/20905628/4572a8d6-bb4d-11e6-9df0-e8219b98075c.gif)

**Comment by carsongross** [comment] 2016-12-05 22:53
I think the problem is that isScrolledIntoView() is being called and is returning false because the table is hidden.  Kind of a corner case, but I should fix it.

**Comment by fullergalway** [comment] 2016-12-21 06:18
Possibly same as #144 ?

**Comment by carsongross** [comment] 2016-12-22 21:42
Yep, it is.  Will merge that fix soon.  :)

**Comment by carsongross** [comment] 2016-12-28 19:18
fix merged into development

**Closed by carsongross** 2016-12-28 19:18 UTC
