### ISSUE TITLE
ic-replace-target problem

### ISSUE THREAD

**Issue by ygwain** [LeadDyno/intercooler-js#176] opened 2017-03-03 15:13 UTC
I have a problem with **ic-replace-target**. I'm trying to reinitialize date pickers inside the element but it's not working.
http://jsfiddle.net/s1ouw4yr/22/

**Comment by ygwain** [comment] 2017-03-03 15:42
Quick fix that worked for me. I've replaced this line
https://github.com/LeadDyno/intercooler-js/blob/master/src/intercooler.js#L1214
to
target = $(contentToSwap).replaceAll(target);

**Comment by OvermindDL1** [comment] 2017-03-04 01:14
> IMHO after calling target.replaceWith(contentToSwap) variable target contains old (detached from the DOM) element.

Hah, I think I mentioned that last year, not fixed yet?  :-)

**Comment by carsongross** [comment] 2017-03-06 19:00
Would it be possible to get a unit test demonstrating the issue?


On March 3, 2017 at 5:14:28 PM, OvermindDL1 (notifications@github.com)
wrote:

IMHO after calling target.replaceWith(contentToSwap) variable target
contains old (detached from the DOM) element.

Hah, I think I mentioned that last year, not fixed yet? :-)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/176#issuecomment-284113331>,
or mute the thread

**Comment by ygwain** [comment] 2017-03-09 18:51
Do you want it as PR or a chunk of code would suffice?

**Comment by carsongross** [comment] 2017-03-09 18:56
A pull request against development would be great!


On March 9, 2017 at 10:51:42 AM, ygwain (notifications@github.com) wrote:

Do you want it as PR or a chunk of code would suffice?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/176#issuecomment-285443981>,
or mute the thread

**Comment by ygwain** [comment] 2017-03-11 11:46
I hope this will help.

**Comment by jsampson-gw** [comment] 2017-04-14 22:41
I just encountered this bug as well. It was pretty confusing because some of my IC requests were resulting in correct ready() processing and others weren't, but when debugging I saw the ready() function being called in every case, and it even appeared to be called with the right element because it had the expected id attribute. Eventually I decided to simplify the page down to the bare minimum elements to reproduce the bug, and that's when I realized all of the problematic IC requests were using ic-replace-target. Came here to file a bug, found this one, and can confirm that @ygwain's unit test looks like exactly case that I'm hitting -- and is much nicer than the clunky mess I was about to send you! :)

**Comment by carsongross** [comment] 2017-04-15 03:25
Really sorry about the bug!


On April 14, 2017 at 3:41:04 PM, jsampson-gw (notifications@github.com)
wrote:

I just encountered this bug as well. It was pretty confusing because some
of my IC requests were resulting in correct ready() processing and others
weren't, but when debugging I saw the ready() function being called in
every case, and it even appeared to be called with the right element
because it had the expected id attribute. Eventually I decided to simplify
the page down to the bare minimum elements to reproduce the bug, and that's
when I realized all of the problematic IC requests were using
ic-replace-target. Came here to file a bug, found this one, and can confirm
that @ygwain <https://github.com/ygwain>'s unit test looks like exactly
case that I'm hitting -- and is much nicer than the clunky mess I was about
to send you! :)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/176#issuecomment-294250098>,
or mute the thread

**Comment by jsampson-gw** [comment] 2017-04-17 23:44
In my case, it turned out to be easy to change the problematic Intercooler calls in order to not use ic-replace-target (simply rendering the contents of the target div instead of rendering the div together with its contents). I do still use ic-replace-target in another place that will be harder to redesign, but for the moment there isn't any critical ready() logic that applies to that other place. So I look forward to getting the fix in a future release, but it's no longer a serious issue for me right now.

**Comment by jsampson-gw** [comment] 2017-05-23 21:47
That "another place" I mentioned does need some ready() logic now. :) Any update on getting this fix merged?

**Comment by carsongross** [comment] 2017-05-24 17:37
I believe this fix is in the latest release.

**Comment by jsampson-gw** [comment] 2017-05-24 18:08
Got it, yes! Upgrading from 1.1.1 to 1.1.2 fixes my issue. 👍

**Comment by carsongross** [comment] 2017-05-24 18:13
![Feels Good Man](http://static1.fjcdn.com/comments/Pc+master+race+feels+good+man+_409b8e527ff399148ab1486d60276ae5.png)

**Closed by carsongross** 2017-05-24 18:13 UTC
