### ISSUE TITLE
Event propagation is stopped when default is prevented

### ISSUE THREAD

**Issue by JavierParra** [LeadDyno/intercooler-js#150] opened 2016-12-20 19:52 UTC
When intercooler prevents the default behaviour it also stops propagation (by returning false to the jQuery event handler) therefore preventing any further use my application could have for that event.

**Comment by carsongross** [comment] 2016-12-28 19:20
I'm wondering if the fix for this will have unintended consequences for existing users.  What do you think?

**Comment by JavierParra** [comment] 2016-12-28 19:34
I can see someone declaring a document-wide click handler for something else and relying on it not being propagated for intercooler links.

But in that scenario, they'd encounter unexpected behavior when not setting an "href" attribute.

I agree it has a chance to break someone's code but I do believe it's important to have homogeneous behavior and not break a standard API.

Maybe add a "breaking changes" notice in the changelog?

**Comment by carsongross** [comment] 2016-12-28 23:14
Mmm.

Let me think about it a few days.  Another option would be to make it an,
er, option, via a configuration attribute or meta tag...

Mmm.


On December 28, 2016 at 11:34:32 AM, JavierParra (notifications@github.com)
wrote:

I can see someone declaring a document-wide click handler for something
else and relying on it not being propagated for intercooler links.

But in that scenario, they'd encounter unexpected behavior when not setting
an "href" attribute.

I agree it has a chance to break someone's code but I do believe it's
important to have homogeneous behavior and not break a standard API.

Maybe add a "breaking changes" notice in the changelog?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/LeadDyno/intercooler-js/issues/150#issuecomment-269528158>,
or mute the thread

**Closed** 2017-06-19 05:26 UTC
